from __future__ import annotations
from pathlib import PurePosixPath
from typing import Protocol, runtime_checkable, Any, Optional, AsyncIterator, Self


@runtime_checkable
class AsyncStorageProtocol(Protocol):
    async def get_info(self, path: str) -> dict[str, Any]: ...
    
    async def list_dir(self, path: str) -> AsyncIterator[tuple[str, Optional[dict]]]: ...
    
    async def open(self, path: str, mode: str) -> Any: ...
    
    async def exists(self, path: str) -> bool: ...
    
    async def unlink(self, path: str): ...
    
    async def mkdir(self, path: str, mode: str, parents: bool, exist_ok: bool): ...
    
    async def rename(self, src: str, dest: str): ...


@runtime_checkable
class AsyncVPathProtocol(Protocol):
    @property
    def storage(self) -> AsyncStorageProtocol: ...
    
    async def stat(self): ...
    
    async def iterdir(self) -> AsyncIterator[AsyncVPathProtocol]: ...
    
    def chroot(self) -> Self: ...
    
    async def open(self, mode="r", encoding="utf-8"): ...
    
    async def unlink(self): ...
    
    async def mkdir(self, mode=0o777, parents=False, exist_ok=False): ...
